phpbbireland_base_controller:
    pattern: /portal
    defaults: { _controller: phpbbireland.portal.controller:portal }

phpbbireland_base_controller:
    pattern: /portal.php
    defaults: { _controller: phpbbireland.portal.controller:portal }

phpbbireland_page_controller:
    pattern: /portal/page/{page}
    defaults: { _controller: phpbbireland.portal.controller:portal }
    requirements:
        page:        \d+


phpbbireland_redirect_controller:
    pattern: /rules
    defaults: { _controller: phpbbireland.portal.controller:rules }

phpbbireland_redirect_controller:
    pattern: /rules.php
    defaults: { _controller: phpbbireland.portal.controller:rules }