phpbbireland_controller:
    pattern: /portal
    defaults: { _controller: phpbbireland.portal.main:build_portal }

phpbbireland_controller:
    pattern: /portal.php
    defaults: { _controller: phpbbireland.portal.main:build_portal }

# This is currently not supported yet
phpbbireland_pages_controller:
    pattern: /portal/{page}
    defaults: { _controller: phpbbireland.portal.main:build_portal, page: "portal" }

# Redirect to portal by default
phpbbireland_redirect_controller:
    pattern: /
    defaults: { _controller: phpbbireland.portal.main:build }
