imports:
    - { resource: controller.yml }
    - { resource: blocks.yml }
    - { resource: tables.yml }

services:
    phpbbireland.portal.main:
        class: phpbbireland\portal\controller\main
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%

    phpbbireland.core.helpers.portal:
        class: phpbbireland\core\helpers\portal

    phpbbireland.core.helpers.tables:
        class: phpbbireland\core\helpers\tables
        arguments:
            - %tables.phpbbireland.k_config%
            - %tables.phpbbireland.k_blocks%
            - %tables.phpbbireland.k_pages%
            - %tables.phpbbireland.k_menus%
            - %tables.phpbbireland.k_resources%
            - %tables.phpbbireland.k_newsfeeds%
            - %tables.phpbbireland.k_youtube%
            - %tables.phpbbireland.k_acronyms%

    phpbbireland.blocks_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: phpbbireland.blocks }

    phpbbireland.portal.listner:
        class: phpbbireland\portal\event\main_listener
        arguments:
             - @controller.helper
             - @template
             - @user
        tags:
            - { name: event.listener }