imports:
    - { resource: tables.yml }

services:
    phpbbireland.portal.controller:
        class: phpbbireland\portal\controller\main_controller
        arguments:
            - @config
            - @template
            - @user
            - @controller.helper
            - @phpbbireland.portal
            - %core.root_path%
            - %core.php_ext%
            
    phpbbireland.portal:
        class: phpbbireland\portal\portal
        arguments:
            - @auth
            - @cache
            - @config
            - @request
            - @template
            - @user
            - @content.visibility
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%

    phpbbireland.portal.listener:
        class: phpbbireland\portal\event\listener
        arguments:
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }

    phpbbireland.core.helpers.portal:
        class: phpbbireland\core\helpers\portal

    phpbbireland.core.helpers.tables:
        class: phpbbireland\core\helpers\tables
        arguments:
            - %tables.phpbbireland.k_config%
            - %tables.phpbbireland.k_blocks%
            - %tables.phpbbireland.k_pages%
            - %tables.phpbbireland.k_menus%
            - %tables.phpbbireland.k_resources%

    phpbbireland.blocks_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: phpbbireland.blocks }

